default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV["SCHEMA_TO_GO_URL"] %>
  database: legendary_pancake_development

test:
  <<: *default
  database: legendary_pancake_test

production:
  <<: *default
  url: <%= ENV["SCHEMA_TO_GO_URL"] %>
  database: legendary_pancake_production
